// examples/user-management/refine-user-management/src/components/account.tsx
import { BaseKey, useGetIdentity, useLogout } from '@refinedev/core'
import { useForm } from '@refinedev/react-hook-form'
import { Controller } from 'react-hook-form'

import Avatar from './avatar'

interface IUserIdentity {
  id?: BaseKey
  username: string
  name: string
}

export interface IProfile {
  id?: string
  username?: string
  website?: string
  avatar_url?: string
}

export default function Account() {
  const { data: userIdentity } = useGetIdentity<IUserIdentity>()

  const { mutate: logOut } = useLogout()

  const {
    refineCore: { formLoading, query, onFinish },
    register,
    control,
    handleSubmit,
  } = useForm<IProfile>({
    refineCoreProps: {
      resource: 'profiles',
      action: 'edit',
      id: userIdentity?.id,
      redirect: false,
      onMutationError: (data) => alert(data?.message),
    },
  })

  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      <form onSubmit={handleSubmit(onFinish)} className="form-widget">
        <Controller
          control={control}
          name="avatar_url"
          render={({ field }) => {
            return (
              <Avatar
                url={field.value}
                size={150}
                onUpload={(filePath) => {
                  onFinish({
                    ...query?.data?.data,
                    avatar_url: filePath,
                    onMutationError: (data: { message: string }) => alert(data?.message),
                  })
                  field.onChange({
                    target: {
                      value: filePath,
                    },
                  })
                }}
              />
            )
          }}
        />
        <div>
          <label htmlFor="email">Email</label>
          <input id="email" name="email" type="text" value={userIdentity?.name} disabled />
        </div>
        <div>
          <label htmlFor="username">Name</label>
          <input id="username" type="text" {...register('username')} />
        </div>
        <div>
          <label htmlFor="website">Website</label>
          <input id="website" type="url" {...register('website')} />
        </div>

        <div>
          <button className="button block primary" type="submit" disabled={formLoading}>
            {formLoading ? 'Loading ...' : 'Update'}
          </button>
        </div>

        <div>
          <button className="button block" type="button" onClick={() => logOut()}>
            Sign Out
          </button>
        </div>
      </form>
    </div>
  )
}

// examples/user-management/nuxt3-user-management/components/Account.vue
<template>
  <form class="form-widget" @submit.prevent="updateProfile">
    <Avatar v-model:path="avatar_path" @upload="updateProfile" :size="10" />
    <div>
      <label for="email">Email</label>
      <input id="email" type="text" :value="user.email" disabled />
    </div>
    <div>
      <label for="username">Name</label>
      <input id="username" type="text" v-model="username" />
    </div>
    <div>
      <label for="website">Website</label>
      <input id="website" type="url" v-model="website" />
    </div>

    <div>
      <input
        type="submit"
        class="button block primary"
        :value="loading ? 'Loading ...' : 'Update'"
        :disabled="loading"
      />
    </div>

    <div>
      <button type="button" class="button block" @click="signOut">Sign Out</button>
    </div>
  </form>
</template>

<script setup>
const supabase = useSupabaseClient()

const loading = ref(false)
const username = ref('')
const website = ref('')
const avatar_path = ref('')

const user = useSupabaseUser()
const { data: profile } = await useAsyncData('profile', async () => {
  loading.value = true
  const { data } = await supabase
    .from('profiles')
    .select(`username, website, avatar_url`)
    .eq('id', user.value.id)
    .single()

  loading.value = false
  return data
})

if (profile.value.username) {
  username.value = profile.value.username
  website.value = profile.value.website
  avatar_path.value = profile.value.avatar_url
}

async function updateProfile() {
  try {
    loading.value = true
    const user = useSupabaseUser()
    const updates = {
      id: user.value.id,
      username: username.value,
      website: website.value,
      avatar_url: avatar_path.value,
      updated_at: new Date(),
    }
    let { error } = await supabase.from('profiles').upsert(updates)
    if (error) throw error
  } catch (error) {
    alert(error.message)
  } finally {
    loading.value = false
  }
}

const supabaseAuth = useSupabaseAuthClient()
async function signOut() {
  try {
    loading.value = true
    let { error } = await supabaseAuth.auth.signOut()
    if (error) throw error
  } catch (error) {
    alert(error.message)
  } finally {
    loading.value = false
  }
}
</script>
