// examples/user-management/ionic-vue-user-management/src/App.vue
<template>
  <ion-app>
    <ion-router-outlet />
  </ion-app>
</template>

<script setup lang="ts">
import { IonApp, IonRouterOutlet, useIonRouter } from '@ionic/vue'
import { onUnmounted } from 'vue'

import { store } from './store'
import { supabase } from './supabase'

const router = useIonRouter()

supabase.auth.getClaims().then(({ data: { claims } }) => {
  store.user = claims
})

const {
  data: { subscription },
} = supabase.auth.onAuthStateChange((_event, session) => {
  store.user = session?.user ?? null
  if (session?.user) {
    router.replace('/account')
  } else {
    router.replace('/')
  }
})

onUnmounted(() => {
  subscription.unsubscribe()
})
</script>

// examples/user-management/expo-push-notifications/App.tsx
import 'react-native-url-polyfill/auto'

import { Session } from '@supabase/supabase-js'
import { useEffect, useState } from 'react'
import { View } from 'react-native'

import Account from './components/Account'
import Auth from './components/Auth'
import { supabase } from './lib/supabase'

export default function App() {
  const [session, setSession] = useState<Session | null>(null)

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
    })

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

  return (
    <View>
      {session && session.user ? <Account key={session.user.id} session={session} /> : <Auth />}
    </View>
  )
}
